### ISSUE TITLE
Default port

### ISSUE THREAD

**Issue by themakerbro** [Dan-in-CA/OSPi#113]
Hey, thanks for the great port os OS to Python!  As someone new to OS/OSPi I followed the instructions:
http://rayshobby.net/mediawiki/index.php/Python_Interval_Program_for_OSPi#Installation

But as I did:
```sudo python ospi.py```
I got:
```
Traceback (most recent call last):
  File "ospi.py", line 214, in <module>
    app.run()
  File "ospi.py", line 162, in run
    return web.httpserver.runsimple(func, ('0.0.0.0', port))
  File "/home/pi/clouden-master/web/httpserver.py", line 157, in runsimple
    server.start()
  File "/home/pi/clouden-master/web/wsgiserver/__init__.py", line 1753, in start
    raise socket.error(msg)
socket.error: No socket could be created
```

Which is due to another service using the default port 80 (apache2, of course).  So as a suggestion, you can update the instructions to either run OSPi/SIP on a different port by default, or tell the user to issue a:

`sudo service apache2 stop`

I think apache2 is set to run by default on the latest version of Raspbian, but I'm not 100% sure as I was using the OS image.

**Comment by Dan-in-CA** [comment]
thanks for the input.

I tested an installation of the latest Raspbian 3,18 and when I tried your suggestion of stopping a running apache2 service I got a message "apachie2: unrecognized service"
If apache2 was running from an init.d script, the script would need to be disabled otherwise apache2 would restart if the system was rebooted.

Originally the Python program was set to use port 8080 as default because Samer's mobile app used apache on port 80 but that version of the app is really old and is no longer supported.

Also the documentation on Ray's hobby is somewhat out of date. The latest docs are at:
https://github.com/Dan-in-CA/OSPi/wiki
